# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170703_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.ProductAttribute'),
        ),
    ]
